### ISSUE TITLE
Xcode 14.0 Swift 5.7 compilation error

### ISSUE THREAD

**Issue by this-is-daniru** [klarna/klarna-mobile-sdk#159]
**Describe the bug**
Package fails to compile with current Xcode Version 14.0 (14A309) with Swift 5.7 run on macOS Monterey 12.6
Compiler points out two errors:

> Failed to build module 'KlarnaMobileSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)'). Please select a toolchain which matches the SDK.

>@objc public protocol KlarnaStandaloneWebViewDelegate : ObjectiveC.NSObject - Inheritance from non-protocol type 'NSObject'

**To Reproduce**
1. Start new Xcode project on Xcode 14 with Swift 5.7 toolchain
2. Add klarna-mobile-sdk package
3. import KlarnaMobileSDK anywhere in the project
4. see error

**Expected behavior**
Project compiles on current Xcode version.

**Screenshots**
![Screenshot 2022-09-26 at 13 53 48](https://user-images.githubusercontent.com/25991754/192281596-d2839683-64ad-401b-90e5-51bad1e9c83a.png)
![Screenshot 2022-09-26 at 14 00 06](https://user-images.githubusercontent.com/25991754/192282869-067e2be9-8f4e-40ea-9904-892db4c68342.png)

**Device and version:**
 - Device: Any iOS Device, Xcode run on macOS Monterey 12.6
 - OS version: Any iOS Version
 - Klarna In-App SDK version 2.2.0, 2.3.0

**Merchant Name**
Dashl

**Impact Level**
Issue blocking development

**Additional context**
Reproduced on another macOS with same Xcode version, as well as Xcode 14.1 beta 2.
Also no longer working on Xcode version 13.1 (with toolchain for Swift 5.5.1), displaying different error message.
![Screenshot 2022-09-26 at 16 01 50](https://user-images.githubusercontent.com/25991754/192312567-777bf564-ca47-4cf8-80d9-6e4deff7a5af.png)

**Comment by twprzybysz** [comment]
+1

**Comment by polar133** [comment]
Hi @this-is-daniru @twprzybysz. 

Thanks for the information. We just released a new version compiled using the latest stable version of Xcode (14.0.1). Please give it a try and let us know how it goes.

**Comment by twprzybysz** [comment]
Hello @polar133,

I'm checking the SDK on Xcode 13.3.1 and I'm getting following message:
`Failed to build module 'KlarnaMobileSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)'). Please select a toolchain which matches the SDK.`
I assume that you're preparing SDK with latest sdk, breaking support to older swift versions.

**Comment by twprzybysz** [comment]
@polar133 is `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` set? If no, then this is the case.

**Comment by polar133** [comment]
Yes. it's built with that setting enabled. Should be compatible with any Xcode > 12. Also, we have the subspec for forcing a built using Xcode 13  (https://github.com/klarna/klarna-mobile-sdk/blob/master/KlarnaMobileSDK.podspec#L25)

**Comment by this-is-daniru** [comment]
The issue persists with version 2.3.1 (Xcode 14.0) although with different error message which now reads
`Failed to build module 'KlarnaMobileSDK' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug`

Going back to version 2.2.3 fixes the issue.

**Comment by polar133** [comment]
Thanks. We are checking what's the problem.

**Comment by twprzybysz** [comment]
@polar133 I forgot to mention that I'm trying to use Klarna SDK by spm.

**Comment by twprzybysz** [comment]
I'm attaching demo project which generates an error:
[TestKlarna.zip](https://github.com/klarna/klarna-mobile-sdk/files/9664312/TestKlarna.zip)

Every run of iOS project shows:
`/.../KlarnaMobileSDK.framework/Modules/KlarnaMobileSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface:21:8: No such module '_StringProcessing'`
`/.../ContentView.swift:9:8: Failed to build module 'KlarnaMobileSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.`

Xcode 13.3.1
Minimum iOS version:  iOS 12

**Comment by polar133** [comment]
Thanks @twprzybysz !

**Comment by polar133** [comment]
Hi, just for some updates. We are working on a possible fix in the next release, which hopefully, will be available later today. Meanwhile, we will delete the last version (2.3.1) since it has an issue with Xcode 14.

**Comment by polar133** [comment]
@twprzybysz @this-is-daniru Hi, we re-release version 2.3.1 with a fix. Please give it a try; hopefully, this should work on both Xcode 13 and 14. 🤞

**Comment by this-is-daniru** [comment]
Hi, the re-release might have caused some issues with SPM revision number. 
As of now I'm not able to check out package with v 2.3.1 due to error:
`error project: Revision a86ebeef2fd9bc18bf9c31765dfd6bee73646285 for klarna-mobile-sdk remoteSourceControl https://github.com/klarna/klarna-mobile-sdk version 2.3.1 does not match previously recorded value 82e31ed72eb77a21cc486317313732256cfd345f
`

**Comment by twprzybysz** [comment]
@polar133 I confirm that issue is resolved, thanks for quick response.

**Comment by uszynskimateusz** [comment]
HI @polar133, 
I checked now on Xcode 13.4.1 and it is ok. Everything is working.
